### ISSUE TITLE
artisan autocompletion doesn't work

### ISSUE THREAD

**Issue by mikeziri** [jerguslejko/zsh-symfony-completion#1]
I successfully installed and had autocompletion on composer and valet but not on artisan.

I have an alias for artisan='php artisan'

and on a dir with artisan in, after pressing tab it says:

> artisan (eval):1: command not found: artisan

can you understand what's wrong?

**Comment by jerguslejko** [comment]
Hey @mwmdev, thanks for feedback!

I took a look and you are right. The plugin was not able to work correctly if the _alias name_ was the same as the _tool name_.

I fixed this by reversing the mechanism for determining whether the tool is installed locally or globally.

Anyways, this has now been fixed in 0a82dea64e6124dec9afb159367f63a3cab4151f and tagged as **0.0.1**.

Please, can you verify that this has actually fixed the issue? Thank you 🌵

**Comment by mikeziri** [comment]
perfect!

tnx
